import AppKit
import Carbon.HIToolbox
import OSLog

/// Puts text where the cursor is: on the pasteboard, ⌘V, then the user's clipboard back.
/// Paste is the one path that works in every app; typing characters fights autocomplete, and
/// Accessibility text insertion works in native text views only.
enum Paste {
    /// Marks Tony's synthetic key events, so the hotkey tap lets them through.
    nonisolated static let marker: Int64 = 0x746F_6E79  // "tony"
    /// Slow apps (Electron, browsers) read the pasteboard after ⌘V returns: restoring sooner pastes the old clipboard.
    static let restoreDelay: Duration = .milliseconds(600)

    private static var saved: [NSPasteboardItem]?
    /// The pasteboard's change count right after Tony's last write.
    private static var ours = 0
    /// Puts the user's clipboard back; quitting waits for it.
    private(set) static var restore: Task<Void, Never>?
    private static let log = Logger(subsystem: "com.bestboyhq.tony", category: "insert")

    /// False when secure input blocks synthetic paste: the caller keeps the text one click away.
    static func paste(_ text: String) -> Bool {
        guard !SecureInput.isOn else { return false }
        let pasteboard = NSPasteboard.general
        // A dictation right after another keeps the first one's saved clipboard, which is the user's,
        // unless the user copied something in between.
        if restore == nil || pasteboard.changeCount != ours { saved = snapshot(pasteboard) }
        restore?.cancel()

        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        // Clipboard managers skip these (nspasteboard.org), so dictations stay out of their history.
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
        pasteboard.clearContents()
        pasteboard.writeObjects([item])
        ours = pasteboard.changeCount

        pressCommandV()

        restore = Task {
            try? await Task.sleep(for: restoreDelay)
            guard !Task.isCancelled else { return }
            // Someone copied in between: theirs wins, and the old clipboard is gone for good.
            if pasteboard.changeCount == ours, let saved {
                pasteboard.clearContents()
                pasteboard.writeObjects(saved)
            }
            saved = nil
            restore = nil
        }
        return true
    }

    /// Copies every item with every type, so restoring brings back files, images, and rich text too.
    /// ponytail: reads every type eagerly, so a huge promised item (a big image) costs its full size in memory.
    private static func snapshot(_ pasteboard: NSPasteboard) -> [NSPasteboardItem] {
        (pasteboard.pasteboardItems ?? []).map { item in
            let copy = NSPasteboardItem()
            for type in item.types {
                if let data = item.data(forType: type) { copy.setData(data, forType: type) }
            }
            return copy
        }
    }

    private static func pressCommandV() {
        // No local event suppression: it would swallow the hotkey's release when it comes right after.
        let source = CGEventSource(stateID: .combinedSessionState)
        source?.userData = marker
        let key = vKeyCode()
        for down in [true, false] {
            let event = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: down)
            event?.flags = .maskCommand
            event?.setIntegerValueField(.eventSourceUserData, value: marker)
            event?.post(tap: .cghidEventTap)
        }
    }

    /// The key that types "v" while ⌘ is held in the active layout, so Dvorak pastes instead of firing
    /// another shortcut. Layouts with no "v" (Russian, Greek) get the ANSI V key: macOS matches shortcuts
    /// by QWERTY position there. On the main thread: TIS asserts the main queue on macOS 14+.
    static func vKeyCode(layout: TISInputSource? = TISCopyCurrentKeyboardLayoutInputSource()?.takeRetainedValue()) -> CGKeyCode {
        let ansiV = CGKeyCode(kVK_ANSI_V)
        guard let layout, let pointer = TISGetInputSourceProperty(layout, kTISPropertyUnicodeKeyLayoutData) else { return ansiV }
        let data = Unmanaged<CFData>.fromOpaque(pointer).takeUnretainedValue() as Data
        return data.withUnsafeBytes { raw -> CGKeyCode in
            guard let keys = raw.baseAddress?.assumingMemoryBound(to: UCKeyboardLayout.self) else { return ansiV }
            for code in 0..<UInt16(128) {
                var deadKeys: UInt32 = 0
                var length = 0
                var chars = [UniChar](repeating: 0, count: 4)
                let status = UCKeyTranslate(keys, code, UInt16(kUCKeyActionDown), UInt32((cmdKey >> 8) & 0xFF), UInt32(LMGetKbdType()),
                                            OptionBits(kUCKeyTranslateNoDeadKeysBit), &deadKeys, chars.count, &length, &chars)
                if status == noErr, length == 1, chars[0] == UniChar(("v" as Unicode.Scalar).value) { return CGKeyCode(code) }
            }
            return ansiV
        }
    }
}
